# Apache Deployment
apiVersion: apps/v1
kind: Deployment     # kind specifies the type of Kubernetes object that the manifest represents
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 10
  selector:
    matchLabels:
      app: apache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
---
# Apache Service
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use LoadBalancer for cloud environments
